services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
